// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AdminAddComputerPlayer(arg1:number,arg2:string,arg3:number):Promise<Record<string, any>>;

export function AdminBanIP(arg1:number,arg2:string):Promise<boolean>;

export function AdminBanName(arg1:number,arg2:string):Promise<boolean>;

export function AdminBanPlayer(arg1:number,arg2:number,arg3:boolean):Promise<boolean>;

export function AdminBans(arg1:number):Promise<Record<string, any>>;

export function AdminForceReset(arg1:number):Promise<boolean>;

export function AdminHostedPorts():Promise<Array<number>>;

export function AdminKick(arg1:number,arg2:number):Promise<boolean>;

export function AdminListPlayers(arg1:number):Promise<Array<Record<string, any>>>;

export function AdminRoomStatus(arg1:number):Promise<Record<string, any>>;

export function AdminSetLocked(arg1:number,arg2:boolean):Promise<boolean>;

export function AdminSetMaxClients(arg1:number,arg2:number):Promise<boolean>;

export function AdminUnban(arg1:number,arg2:string):Promise<boolean>;

export function AppendV2DebugLog(arg1:string):Promise<boolean>;

export function BackendInfo():Promise<Record<string, any>>;

export function BridgePort():Promise<number>;

export function ClearV2DebugLog():Promise<boolean>;

export function CpolarConfigPath():Promise<string>;

export function CpolarInitAccounts():Promise<Record<string, any>>;

export function CpolarStartTCP(arg1:string,arg2:number):Promise<Record<string, any>>;

export function CpolarStartTCPForTarget(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CpolarStatus():Promise<backend.CpolarStatus>;

export function CpolarStop(arg1:string):Promise<boolean>;

export function CpolarStopAll():Promise<boolean>;

export function CreateGraphwar2Room(arg1:string,arg2:number,arg3:boolean):Promise<Record<string, any>>;

export function CreateRoom(arg1:string,arg2:number):Promise<number>;

export function Graphwar2DLLInfo():Promise<backend.GW2DLLInfo>;

export function Graphwar2HostedOfficialRoom():Promise<Record<string, any>>;

export function Graphwar2LobbyRooms():Promise<Record<string, any>>;

export function Graphwar2LocalRooms():Promise<Record<string, any>>;

export function Graphwar2OfficialPublisherStatus():Promise<backend.Graphwar2PublisherStatus>;

export function LastError():Promise<string>;

export function ProbeGraphwar2Room(arg1:string,arg2:number):Promise<backend.Graphwar2RoomProbeResult>;

export function PublishGraphwar2OfficialRoom(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function SetV2DebugEnabled(arg1:boolean):Promise<boolean>;

export function StartBackend(arg1:string):Promise<number>;

export function StartBackendOn(arg1:string,arg2:number,arg3:number):Promise<number>;

export function StopGraphwar2OfficialPublisher():Promise<boolean>;

export function Translate(arg1:string,arg2:string):Promise<string>;

export function V2BridgePort():Promise<number>;

export function V2DebugEnabled():Promise<boolean>;

export function V2DebugLogPath():Promise<string>;
