// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminAddComputerPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminAddComputerPlayer'](arg1, arg2, arg3);
}

export function AdminBanIP(arg1, arg2) {
  return window['go']['main']['App']['AdminBanIP'](arg1, arg2);
}

export function AdminBanName(arg1, arg2) {
  return window['go']['main']['App']['AdminBanName'](arg1, arg2);
}

export function AdminBanPlayer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminBanPlayer'](arg1, arg2, arg3);
}

export function AdminBans(arg1) {
  return window['go']['main']['App']['AdminBans'](arg1);
}

export function AdminForceReset(arg1) {
  return window['go']['main']['App']['AdminForceReset'](arg1);
}

export function AdminHostedPorts() {
  return window['go']['main']['App']['AdminHostedPorts']();
}

export function AdminKick(arg1, arg2) {
  return window['go']['main']['App']['AdminKick'](arg1, arg2);
}

export function AdminListPlayers(arg1) {
  return window['go']['main']['App']['AdminListPlayers'](arg1);
}

export function AdminRoomStatus(arg1) {
  return window['go']['main']['App']['AdminRoomStatus'](arg1);
}

export function AdminSetLocked(arg1, arg2) {
  return window['go']['main']['App']['AdminSetLocked'](arg1, arg2);
}

export function AdminSetMaxClients(arg1, arg2) {
  return window['go']['main']['App']['AdminSetMaxClients'](arg1, arg2);
}

export function AdminUnban(arg1, arg2) {
  return window['go']['main']['App']['AdminUnban'](arg1, arg2);
}

export function AppendV2DebugLog(arg1) {
  return window['go']['main']['App']['AppendV2DebugLog'](arg1);
}

export function BackendInfo() {
  return window['go']['main']['App']['BackendInfo']();
}

export function BridgePort() {
  return window['go']['main']['App']['BridgePort']();
}

export function ClearV2DebugLog() {
  return window['go']['main']['App']['ClearV2DebugLog']();
}

export function CpolarConfigPath() {
  return window['go']['main']['App']['CpolarConfigPath']();
}

export function CpolarInitAccounts() {
  return window['go']['main']['App']['CpolarInitAccounts']();
}

export function CpolarStartTCP(arg1, arg2) {
  return window['go']['main']['App']['CpolarStartTCP'](arg1, arg2);
}

export function CpolarStartTCPForTarget(arg1, arg2) {
  return window['go']['main']['App']['CpolarStartTCPForTarget'](arg1, arg2);
}

export function CpolarStatus() {
  return window['go']['main']['App']['CpolarStatus']();
}

export function CpolarStop(arg1) {
  return window['go']['main']['App']['CpolarStop'](arg1);
}

export function CpolarStopAll() {
  return window['go']['main']['App']['CpolarStopAll']();
}

export function CreateGraphwar2Room(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGraphwar2Room'](arg1, arg2, arg3);
}

export function CreateRoom(arg1, arg2) {
  return window['go']['main']['App']['CreateRoom'](arg1, arg2);
}

export function Graphwar2DLLInfo() {
  return window['go']['main']['App']['Graphwar2DLLInfo']();
}

export function Graphwar2HostedOfficialRoom() {
  return window['go']['main']['App']['Graphwar2HostedOfficialRoom']();
}

export function Graphwar2LobbyRooms() {
  return window['go']['main']['App']['Graphwar2LobbyRooms']();
}

export function Graphwar2LocalRooms() {
  return window['go']['main']['App']['Graphwar2LocalRooms']();
}

export function Graphwar2OfficialPublisherStatus() {
  return window['go']['main']['App']['Graphwar2OfficialPublisherStatus']();
}

export function LastError() {
  return window['go']['main']['App']['LastError']();
}

export function ProbeGraphwar2Room(arg1, arg2) {
  return window['go']['main']['App']['ProbeGraphwar2Room'](arg1, arg2);
}

export function PublishGraphwar2OfficialRoom(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishGraphwar2OfficialRoom'](arg1, arg2, arg3);
}

export function SetV2DebugEnabled(arg1) {
  return window['go']['main']['App']['SetV2DebugEnabled'](arg1);
}

export function StartBackend(arg1) {
  return window['go']['main']['App']['StartBackend'](arg1);
}

export function StartBackendOn(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartBackendOn'](arg1, arg2, arg3);
}

export function StopGraphwar2OfficialPublisher() {
  return window['go']['main']['App']['StopGraphwar2OfficialPublisher']();
}

export function Translate(arg1, arg2) {
  return window['go']['main']['App']['Translate'](arg1, arg2);
}

export function V2BridgePort() {
  return window['go']['main']['App']['V2BridgePort']();
}

export function V2DebugEnabled() {
  return window['go']['main']['App']['V2DebugEnabled']();
}

export function V2DebugLogPath() {
  return window['go']['main']['App']['V2DebugLogPath']();
}
